package tubespbo;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date;

/**
 *
 * @author Zhatozs
 */

public class View extends javax.swing.JFrame {
        private int waktumulai = 0;

    
    public void tanggal(){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        labeltanggal.setText(s.format(ys));
    }
    
    private void JamRealTime(){
        
        new Thread(){
            @Override
            public void run(){
                while(waktumulai == 0){
                    Calendar kalender = new GregorianCalendar();
                    int jam = kalender.get(Calendar.HOUR);
                    int menit = kalender.get(Calendar.MINUTE);
                    int detik = kalender.get(Calendar.SECOND);
                    int AMPM = kalender.get(Calendar.AM_PM);
                    String SiangMalam;
                    if (AMPM == 1){
                        SiangMalam = "PM";
                    }else{
                        SiangMalam = "AM";
                    }
                    String JamRealTime = jam + ":" + menit + ":" + detik +" " + SiangMalam;
                    labeljam.setText(JamRealTime);
                }
            }
        }.start();
    }
    private void kosongkan_form(){
        txtNIK.setEditable(true);
        txtNIK.setText(null);
        txtNama.setText(null);
        txtAlamat.setText(null);
        txtTelepon.setText(null);
    }
    
    private void kosongkan_formK(){
        txtNIKK.setEditable(true);
        txtNIKK.setText(null);
        txtNamaK.setText(null);
        txtAlamatK.setText(null);
        txtTelpK.setText(null);
        cbJabatanK.setSelectedItem(this);
    }
    
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No. Telepon");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM databayi";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
                
            }
            tableDataBayi.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    private void tampilkan_dataK(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No. Telepon");
        model.addColumn("Jabatan");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM datakader";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
                
            }
            tableDataKader.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
        tampilkan_dataK();
        kosongkan_formK();
        JamRealTime();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();
        btnInputData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JToggleButton();
        btnInformasi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAbout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnInputDataKader = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnKalkulator = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        panelViewInputData = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataBayi = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        panelViewInformasi = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        panelViewInputDataKader = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNIKK = new javax.swing.JTextField();
        txtAlamatK = new javax.swing.JTextField();
        txtNamaK = new javax.swing.JTextField();
        txtTelpK = new javax.swing.JTextField();
        cbJabatanK = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataKader = new javax.swing.JTable();
        btnTambahK = new javax.swing.JButton();
        btnSimpanK = new javax.swing.JButton();
        btnEditK = new javax.swing.JButton();
        btnHapusK = new javax.swing.JButton();
        btnBatalK = new javax.swing.JButton();
        panelViewKalkulator = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tinggiValue = new javax.swing.JTextField();
        beratValue = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        jlabelbmi = new javax.swing.JLabel();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI POSYANDU");
        setMinimumSize(new java.awt.Dimension(810, 510));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelKiri.setBackground(new java.awt.Color(52, 152, 219));

        btnInputData.setBackground(new java.awt.Color(127, 140, 141));
        btnInputData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInputDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInputDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInputDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInputDataMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-document-40.png"))); // NOI18N
        jLabel2.setText("INPUT DATA");

        javax.swing.GroupLayout btnInputDataLayout = new javax.swing.GroupLayout(btnInputData);
        btnInputData.setLayout(btnInputDataLayout);
        btnInputDataLayout.setHorizontalGroup(
            btnInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInputDataLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInputDataLayout.setVerticalGroup(
            btnInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInputDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnInformasi.setBackground(new java.awt.Color(127, 140, 141));
        btnInformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformasiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInformasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInformasiMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-info-40.png"))); // NOI18N
        jLabel4.setText("INFORMASI");

        javax.swing.GroupLayout btnInformasiLayout = new javax.swing.GroupLayout(btnInformasi);
        btnInformasi.setLayout(btnInformasiLayout);
        btnInformasiLayout.setHorizontalGroup(
            btnInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInformasiLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInformasiLayout.setVerticalGroup(
            btnInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInformasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-male-40.png"))); // NOI18N
        jLabel5.setText("ADMIN POSYANDU");

        btnAbout.setBackground(new java.awt.Color(127, 140, 141));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAboutMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-about-40.png"))); // NOI18N
        jLabel13.setText("ABOUT");

        javax.swing.GroupLayout btnAboutLayout = new javax.swing.GroupLayout(btnAbout);
        btnAbout.setLayout(btnAboutLayout);
        btnAboutLayout.setHorizontalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAboutLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAboutLayout.setVerticalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInputDataKader.setBackground(new java.awt.Color(127, 140, 141));
        btnInputDataKader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputDataKaderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInputDataKaderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInputDataKaderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInputDataKaderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInputDataKaderMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-news-40.png"))); // NOI18N
        jLabel14.setText("INPUT DATA KADER");

        javax.swing.GroupLayout btnInputDataKaderLayout = new javax.swing.GroupLayout(btnInputDataKader);
        btnInputDataKader.setLayout(btnInputDataKaderLayout);
        btnInputDataKaderLayout.setHorizontalGroup(
            btnInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInputDataKaderLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInputDataKaderLayout.setVerticalGroup(
            btnInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInputDataKaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        btnKalkulator.setBackground(new java.awt.Color(127, 140, 141));
        btnKalkulator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKalkulatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKalkulatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKalkulatorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKalkulatorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKalkulatorMouseReleased(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-support-40.png"))); // NOI18N
        jLabel23.setText("KALKULATOR BMI");

        javax.swing.GroupLayout btnKalkulatorLayout = new javax.swing.GroupLayout(btnKalkulator);
        btnKalkulator.setLayout(btnKalkulatorLayout);
        btnKalkulatorLayout.setHorizontalGroup(
            btnKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKalkulatorLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel23)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        btnKalkulatorLayout.setVerticalGroup(
            btnKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKalkulatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInputDataKader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelKiriLayout.createSequentialGroup()
                        .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelKiriLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnLogOut)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(btnInputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnInputDataKader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnLogOut))
        );

        jPanel1.add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 510));

        panelKanan.setBackground(new java.awt.Color(44, 62, 80));
        panelKanan.setLayout(new java.awt.CardLayout());

        panelViewInputData.setBackground(new java.awt.Color(44, 62, 80));
        panelViewInputData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(149, 165, 166));
        jPanel5.setPreferredSize(new java.awt.Dimension(520, 510));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel1.setText("INPUT DATA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 180, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 180, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        panelViewInputData.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, 100));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIK");
        panelViewInputData.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama");
        panelViewInputData.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alamat");
        panelViewInputData.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No. Telepon");
        panelViewInputData.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });
        panelViewInputData.add(txtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 258, -1));
        panelViewInputData.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 258, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        panelViewInputData.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 258, -1));
        panelViewInputData.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 258, -1));

        tableDataBayi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDataBayi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataBayiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataBayi);

        panelViewInputData.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 388, -1, 111));

        btnTambah.setText("Clear");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelViewInputData.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelViewInputData.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelViewInputData.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelViewInputData.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelViewInputData.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 351, -1, -1));

        panelKanan.add(panelViewInputData, "card2");

        panelViewInformasi.setBackground(new java.awt.Color(44, 62, 80));

        jPanel6.setBackground(new java.awt.Color(149, 165, 166));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel3.setText("INFORMASI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 37, Short.MAX_VALUE)))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOKASI : BALAI DESA TAMBAKSARI");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tanggal :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TANGGAL : 25 JULI 2022");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("KEGIATAN VAKSIN BAYI BERIKUTNYA");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Jam :");

        labeltanggal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeltanggal.setForeground(new java.awt.Color(52, 152, 219));
        labeltanggal.setText("tanggal");

        labeljam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeljam.setForeground(new java.awt.Color(52, 152, 219));
        labeljam.setText("jam");

        javax.swing.GroupLayout panelViewInformasiLayout = new javax.swing.GroupLayout(panelViewInformasi);
        panelViewInformasi.setLayout(panelViewInformasiLayout);
        panelViewInformasiLayout.setHorizontalGroup(
            panelViewInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelViewInformasiLayout.createSequentialGroup()
                .addGroup(panelViewInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewInformasiLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelViewInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel21)))
                    .addGroup(panelViewInformasiLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labeltanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labeljam)
                        .addGap(23, 23, 23)))
                .addGap(93, 93, 93))
        );
        panelViewInformasiLayout.setVerticalGroup(
            panelViewInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewInformasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelViewInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel22)
                    .addComponent(labeltanggal)
                    .addComponent(labeljam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(131, 131, 131))
        );

        panelKanan.add(panelViewInformasi, "card3");

        panelViewInputDataKader.setBackground(new java.awt.Color(44, 62, 80));

        jPanel7.setBackground(new java.awt.Color(149, 165, 166));

        jLabel15.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel15.setText("INPUT DATA KADER");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 37, Short.MAX_VALUE)))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NIK");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Alamat");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("No. Telepon");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Jabatan");

        txtNIKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKKActionPerformed(evt);
            }
        });

        cbJabatanK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketua", "Wakil Ketua", "Medis", "Tim Informasi Posyandu" }));
        cbJabatanK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJabatanKActionPerformed(evt);
            }
        });

        tableDataKader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDataKader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataKaderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDataKader);

        btnTambahK.setText("Clear");
        btnTambahK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKActionPerformed(evt);
            }
        });

        btnSimpanK.setText("Simpan");
        btnSimpanK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKActionPerformed(evt);
            }
        });

        btnEditK.setText("Edit");
        btnEditK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKActionPerformed(evt);
            }
        });

        btnHapusK.setText("Hapus");
        btnHapusK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKActionPerformed(evt);
            }
        });

        btnBatalK.setText("Batal");
        btnBatalK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewInputDataKaderLayout = new javax.swing.GroupLayout(panelViewInputDataKader);
        panelViewInputDataKader.setLayout(panelViewInputDataKaderLayout);
        panelViewInputDataKaderLayout.setHorizontalGroup(
            panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelViewInputDataKaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewInputDataKaderLayout.createSequentialGroup()
                        .addComponent(btnSimpanK)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahK)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditK)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusK)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatalK))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelViewInputDataKaderLayout.createSequentialGroup()
                        .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(43, 43, 43)
                        .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIKK)
                            .addComponent(txtNamaK)
                            .addComponent(txtAlamatK, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelViewInputDataKaderLayout.createSequentialGroup()
                        .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJabatanK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelpK, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelViewInputDataKaderLayout.setVerticalGroup(
            panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewInputDataKaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNIKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNamaK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAlamatK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTelpK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbJabatanK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelViewInputDataKaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahK)
                    .addComponent(btnEditK)
                    .addComponent(btnHapusK)
                    .addComponent(btnBatalK)
                    .addComponent(btnSimpanK))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelKanan.add(panelViewInputDataKader, "card4");

        panelViewKalkulator.setBackground(new java.awt.Color(44, 62, 80));

        jPanel8.setBackground(new java.awt.Color(149, 165, 166));

        jLabel24.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel24.setText("KALKULATOR BMI");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 37, Short.MAX_VALUE)))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Tinggi(meter)");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Berat(kilogram)");

        tinggiValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiValueActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jlabelbmi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelbmi.setForeground(new java.awt.Color(255, 255, 255));
        jlabelbmi.setText("BMI");

        javax.swing.GroupLayout panelViewKalkulatorLayout = new javax.swing.GroupLayout(panelViewKalkulator);
        panelViewKalkulator.setLayout(panelViewKalkulatorLayout);
        panelViewKalkulatorLayout.setHorizontalGroup(
            panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelViewKalkulatorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabelbmi)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewKalkulatorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(hitung)
                        .addGap(18, 18, 18)
                        .addComponent(hapus))
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(beratValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(tinggiValue, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelViewKalkulatorLayout.setVerticalGroup(
            panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewKalkulatorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tinggiValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(beratValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelbmi)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelViewKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung)
                    .addComponent(hapus))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panelKanan.add(panelViewKalkulator, "card5");

        jPanel1.add(panelKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 520, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LogIn login = new LogIn();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnInputDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataMouseEntered
        btnInputData.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInputDataMouseEntered

    private void btnInputDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataMouseExited
        btnInputData.setBackground(new Color(127, 140, 141));
    }//GEN-LAST:event_btnInputDataMouseExited

    private void btnInputDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataMouseClicked
        // remove panel
        
        panelKanan.removeAll();
        panelKanan.repaint();
        panelKanan.revalidate();
        
        //add panel
        panelKanan.add(panelViewInputData);
        panelKanan.repaint();
        panelKanan.revalidate();
    }//GEN-LAST:event_btnInputDataMouseClicked

    private void btnInputDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataMousePressed
        btnInputData.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_btnInputDataMousePressed

    private void btnInputDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataMouseReleased
        btnInputData.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInputDataMouseReleased

    private void btnInformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiMouseClicked
          // remove panel
        
        panelKanan.removeAll();
        panelKanan.repaint();
        panelKanan.revalidate();
        
        //add panel
        panelKanan.add(panelViewInformasi);
        panelKanan.repaint();
        panelKanan.revalidate();
    }//GEN-LAST:event_btnInformasiMouseClicked

    private void btnInformasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiMouseEntered
        btnInformasi.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInformasiMouseEntered

    private void btnInformasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiMouseExited
        btnInformasi.setBackground(new Color(127, 140, 141));
    }//GEN-LAST:event_btnInformasiMouseExited

    private void btnInformasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiMousePressed
         btnInformasi.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_btnInformasiMousePressed

    private void btnInformasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformasiMouseReleased
        btnInformasi.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInformasiMouseReleased

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        kosongkan_form();
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            String sql = "INSERT INTO databayi VALUES ('"+txtNIK.getText()+"','"+txtNama.getText()+"','"+txtAlamat.getText()+"','"+txtTelepon.getText()+"')";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..");
            tampilkan_data();
            kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tableDataBayiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataBayiMouseClicked
        int baris = tableDataBayi.rowAtPoint(evt.getPoint());
        String nik = tableDataBayi.getValueAt(baris, 1).toString();
        txtNIK.setText(nik);
        
        String nama = tableDataBayi.getValueAt(baris, 2).toString();
        txtNama.setText(nama);
        
        String alamat = tableDataBayi.getValueAt(baris, 3).toString();
        txtAlamat.setText(alamat);
        
        String telp = tableDataBayi.getValueAt(baris, 4).toString();
        txtTelepon.setText(telp);
    }//GEN-LAST:event_tableDataBayiMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String sql = "UPDATE databayi SET nik='"+txtNIK.getText()+"',nama='"+txtNama.getText()+"',alamat='"+txtAlamat.getText()+"',no_telp='"+txtTelepon.getText()+"' WHERE nik = '"+txtNIK.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
            String sql = "DELETE FROM databayi WHERE nik='"+txtNIK.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        kosongkan_form();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setBackground(new Color(127, 140, 141));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        btnAbout.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseReleased
        btnAbout.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnAboutMouseReleased

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void cbJabatanKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJabatanKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJabatanKActionPerformed

    private void btnInputDataKaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataKaderMouseClicked
        panelKanan.removeAll();
        panelKanan.repaint();
        panelKanan.revalidate();
        
        //add panel
        panelKanan.add(panelViewInputDataKader);
        panelKanan.repaint();
        panelKanan.revalidate();
    }//GEN-LAST:event_btnInputDataKaderMouseClicked

    private void btnInputDataKaderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataKaderMouseEntered
        btnInputDataKader.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInputDataKaderMouseEntered

    private void btnInputDataKaderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataKaderMouseExited
        btnInputDataKader.setBackground(new Color(127, 140, 141));
    }//GEN-LAST:event_btnInputDataKaderMouseExited

    private void btnInputDataKaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataKaderMousePressed
        btnInputDataKader.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_btnInputDataKaderMousePressed

    private void btnInputDataKaderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataKaderMouseReleased
        btnInputDataKader.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnInputDataKaderMouseReleased

    private void txtNIKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKKActionPerformed

    private void btnTambahKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKActionPerformed
        kosongkan_formK();
    }//GEN-LAST:event_btnTambahKActionPerformed

    private void btnSimpanKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKActionPerformed
        try{
            String sql = "INSERT INTO datakader VALUES ('"+txtNIKK.getText()+"','"+txtNamaK.getText()+"','"+txtAlamatK.getText()+"','"+txtTelpK.getText()+"','"+cbJabatanK.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..");
            tampilkan_dataK();
            kosongkan_formK();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanKActionPerformed

    private void btnEditKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKActionPerformed
        try{
            String sql = "UPDATE datakader SET nik='"+txtNIKK.getText()+"',nama='"+txtNamaK.getText()+"',alamat='"+txtAlamatK.getText()+"',no_telp='"+txtTelpK.getText()+"',jabatan='"+cbJabatanK.getSelectedItem()+"' WHERE nik = '"+txtNIKK.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_dataK();
        kosongkan_formK();
    }//GEN-LAST:event_btnEditKActionPerformed

    private void tableDataKaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataKaderMouseClicked
        int baris = tableDataKader.rowAtPoint(evt.getPoint());
        String nik = tableDataKader.getValueAt(baris, 1).toString();
        txtNIKK.setText(nik);
        
        String nama = tableDataKader.getValueAt(baris, 2).toString();
        txtNamaK.setText(nama);
        
        String alamat = tableDataKader.getValueAt(baris, 3).toString();
        txtAlamatK.setText(alamat);
        
        String telp = tableDataKader.getValueAt(baris, 4).toString();
        txtTelpK.setText(telp);
    }//GEN-LAST:event_tableDataKaderMouseClicked

    private void btnHapusKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKActionPerformed
        try{
            String sql = "DELETE FROM datakader WHERE nik='"+txtNIKK.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_dataK();
        kosongkan_formK();
    }//GEN-LAST:event_btnHapusKActionPerformed

    private void btnBatalKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKActionPerformed
        kosongkan_formK();
    }//GEN-LAST:event_btnBatalKActionPerformed

    private void btnKalkulatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulatorMouseClicked
        panelKanan.removeAll();
        panelKanan.repaint();
        panelKanan.revalidate();
        
        //add panel
        panelKanan.add(panelViewKalkulator);
        panelKanan.repaint();
        panelKanan.revalidate();
    }//GEN-LAST:event_btnKalkulatorMouseClicked

    private void btnKalkulatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulatorMouseEntered
        btnKalkulator.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnKalkulatorMouseEntered

    private void btnKalkulatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulatorMouseExited
        btnKalkulator.setBackground(new Color(127, 140, 141));
    }//GEN-LAST:event_btnKalkulatorMouseExited

    private void btnKalkulatorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulatorMousePressed
        btnKalkulator.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_btnKalkulatorMousePressed

    private void btnKalkulatorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulatorMouseReleased
        btnKalkulator.setBackground(new Color(149, 165, 166));
    }//GEN-LAST:event_btnKalkulatorMouseReleased
    //kalkulator BMI
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        double t = Double.parseDouble(tinggiValue.getText());
        double b = Double.parseDouble(beratValue.getText());
       
        double bmi = b / (t * t);
        System.out.println(bmi);
        
        String cal = String.format("%.2f", bmi);
        
        output.setText(cal);
        
        if(bmi <= 18.5){
            output.setOpaque(true);
            output.setBackground(Color.blue);
            jlabelbmi.setForeground(Color.blue);
            jlabelbmi.setText("UnderWeight");
        }else if(bmi <= 24.5){
            output.setOpaque(true);
            output.setBackground(Color.green);
            jlabelbmi.setForeground(Color.green);
            jlabelbmi.setText("Normal");
        }else if(bmi <= 29.5){
            output.setOpaque(true);
            output.setBackground(Color.orange);
            jlabelbmi.setForeground(Color.orange);
            jlabelbmi.setText("OverWeight");
        }else if(bmi >= 30){
            output.setOpaque(true);
            output.setBackground(Color.red);
            jlabelbmi.setForeground(Color.red);
            jlabelbmi.setText("Obesitas");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        beratValue.setText("");
        tinggiValue.setText("");
        output.setText("");
        output.setOpaque(true);
        output.setBackground(null);
        jlabelbmi.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void tinggiValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratValue;
    private javax.swing.JPanel btnAbout;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalK;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditK;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusK;
    private javax.swing.JPanel btnInformasi;
    private javax.swing.JPanel btnInputData;
    private javax.swing.JPanel btnInputDataKader;
    private javax.swing.JPanel btnKalkulator;
    private javax.swing.JToggleButton btnLogOut;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpanK;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahK;
    private javax.swing.JComboBox<String> cbJabatanK;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabelbmi;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField output;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelViewInformasi;
    private javax.swing.JPanel panelViewInputData;
    private javax.swing.JPanel panelViewInputDataKader;
    private javax.swing.JPanel panelViewKalkulator;
    private javax.swing.JTable tableDataBayi;
    private javax.swing.JTable tableDataKader;
    private javax.swing.JTextField tinggiValue;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAlamatK;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNIKK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaK;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTelpK;
    // End of variables declaration//GEN-END:variables
}
